== Introduction and Goals

LoMap es un proyecto de ASW que consiste en la creacion de un sistema en el que los ciudadanos dispongan de un mapa personalizado con lugares, negocios... de la ciudad de Bruselas. Los miembros son: 

* Ruben Diaz Zapico - UO283204  

* Alonso Antuña Gómez-UO282834  

* Javier Novella Tomás-UO282944  

* Sergio Moro Muñiz - UO284622  

* Pablo Fernandez Diaz-UO271116

=== Resumen de Requisitos 

La aplicación se ejecutará en el servidor, y la información del usuario se almacenará en su pod. Asi mismo, habra una base de datos centralizada cuya informacion solo contendra lo necesario para acceder al pod de cada usuario. Todos estos requisitos son compatibles con el proyecto SOLID, ya que la información de los usuarios no se almacena de forma centralizada. 

.Requisitos de alto nivel:
* Los usuarios pueden añadir lugares en categorías diferentes: tiendas, bares, restaurantes, paisajes, monumentos, etc.
* Los usuarios serán capaces de mostrar lugares en una ventana tipo mapa.
* Los usuarios pueden asociar puntuaciones, comentarios, fotos, etc. sobre los lugares añadidos.
* Se podrán gestionar desde la aplicación los accesos a la información que comparten con otros usuarios, como sus amigos o grupos de amigos.
* La información sobre un lugar almacenada por cada usuario no deberá estar centralizada, sino que se almacenará en el pod de cada usuario.
* Si fuese necesario, se podría almacenar alguna información de forma centralizada por razones de rendimiento tratando de respetar la privacidad de los usuarios en la medida que sea posible.
* El sistema permitirá a los usuarios ver lugares e información sobre dichos lugares tomada de sus amigos.
* El sistema permitirá visualizar el mapa incorporando filtros, por ejemplo, por categoría, amigos, etc.

.Caracteristicas opcionales: 
* Permitir a los usuarios crear rutas (por ejemplo, rutas para hacer compras o tomar algo)
* Permitir a los usuarios comparar mapas, por ejemplo, comparar ciertas categorías como sólo restaurantes.
* Permitir a los establecimientos (restaurantes, tiendas, bares, etc. ) crear su propio pod para que otras personas puedan conectarse a ellos.
* Crear un boletín de noticias (newsfeed) a partir de los lugares conectados.
* Añadir características de gamificación (recoger información de lugares, descubrir nuevos lugares, etc. )
* Crear múltiples mapas entre grupos de usuarios (por ejemplo, mapas de familia, de compañeros de viaje, ...)
* Conectar con el libro de direcciones para chequear información sobre lugares o realizar recomendaciones de lugares
* Añadir roles (ciudadano, turista, dueño de negocio,...)
* Oportunidades para dueños de negocios, por ejemplo, crear un mapa con lugares recomendados cerca de un establecimiento, bares para tomar algo después de realizar la compra, etc. 

=== Objetivos de calidad

[options="header",cols="1,2,2"]
|===
|Objetivos de calidad|Motivación|Importancia
| Seguridad | Garantizar la seguridad de los datos del cliente para aumentar su confianza y mantener a salvo su privacidad | Alta
| Robustez | Buen manejo de excepciones para mejorar la experiencia del usuario | Alta
| Usabilidad | La aplicación ha de ser intuitiva y de fácil manejo para gente de todo tipo de nivel | Alta
| Transparencia | Todo el proyecto sera visible | Bajo
| Eficiencia | La aplicación sera lo más eficiente posible usando los menores recursos posibles | Media
|===

=== Stakeholders


[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _Profesores_ | _-Jose Emilio Labra

-Cristian Augusto Alonso

-Irene Cid Rico

-Pablo González_ | _Puesta en practica de los conocimientos y explicaciones realizadas en clase para la realización del proyecto_
| _Clientes_ | _Clientes_ | _Aplicación sencilla, con una buena usabilidad, con todas las funcionalidades requeridas y que protega/asegure los datos introducidos_
| _Administrador_ | _Administrador_ | Manejar una aplicación robusta, bien hecha y eficiente que permita solucionar futuros problemas/errores
| _Equipo_ | _-Javier Novella Tomás

-Ruben Díaz Zapico

-Pablo Fernádez Díaz

-Sergio Moro Muñiz

-Alonso Antuña Gómez_ | Mejorar la técnica de trabajo y cooperación en un equipo de desarrollo
|===
