[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****

Ruben Diaz Zapico - UO283204  

Alonso Antuña Gómez-UO282834  

Javier Novella Tomás-UO282944  

Sergio Moro Muñiz - UO284622  

Pablo Fernandez Diaz-UO271116


Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

[role="arc42help"]

****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders


[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _Profesores_ | _-Jose Emilio Labra

-Cristian Augusto Alonso

-Irene Cid Rico

-Pablo González_ | _Puesta en practica de los conocimientos y explicaciones realizadas en clase para la realización del proyecto_
| _Clientes_ | _Clientes_ | _Aplicación sencilla, con una buena usabilidad, con todas las funcionalidades requeridas y que protega/asegure los datos introducidos_
| _Administrador_ | _Administrador_ | Manejar una aplicación robusta, bien hecha y eficiente que permita solucionar futuros problemas/errores
| _Equipo_ | _-Javier Novella Tomás

-Ruben Díaz Zapico

-Pablo Fernádez Díaz

-Sergio Moro Muñiz

-Alonso Antuña Gómez_ | Mejorar la técnica de trabajo y cooperación en un equipo de desarrollo
|===
