[[section-system-scope-and-context]]
== Alcance y contexto del sistema

=== Contexto empresarial
El objetivo del proyecto es desarrollar un sistema de software llamado “LoMap” donde los ciudadanos puedan tener mapas personalizados sobre lugares y negocios locales en su ciudad.
Por otro lado, en esta aplicación los usuarios pueden agregar ubicaciones en diferentes categorías como:

* Tiendas

*	Barras

* Restaurantes

* Lugares de interés

* Monumentos
Los usuarios también pueden agregar puntajes de revisión, comentarios, imágenes, etc. sobre los lugares agregados.

Nustra app es una red social con la infraestructura "dispersa" en pods que pertenecen al usuario(uno por usuario) en vez de una base de datos centralizada en los servidores de la empresa
se sigue teniendo una base de datos central pero solo se usa para guardar informacion basica del usuario tambien la app hara uso de apis externas

=== Contexto técnico

Nuestra aplicación LoMap sigue los principios de descentralización de datos personales SOLID al almacenar datos personales en el POD independiente de cada usuario.  
El front-end se desarrolla utilizando el framework React, el cual implementa componentes propios diseñados o creados, el lenguaje utilizado para desarrollar diversas funciones en pantalla es TypeScript.   
No usamos nada de Back-End ya que el Front-End se comunica directamente con los PODs de inrupt.

[options="header",cols="1,2"]
|===
| Tecnología         | Descripción
| SOLID    | Principios de descentralización de la aplicación.
| PODs    | Para guardar los datos de los usuarios.
| TYPESCRIPT     | Lenguaje principal de la aplicación.
| REACT     | Framework usado para el Front-End.
| Mapbox    | Api que usamos para los mapas.

|===
