[[section-solution-strategy]]
== Soluciones Estratégicas
Para la realización de LoMap hemos tomado la decisión de desarrollarlo en TypeScript, usando el framework React y el proovedor de pods de inrupt. TypeScript es un superconjunto de JavaScript cuyo punto más resaltable es el uso de tipado.

[role="arc42help"]
.Restricciones tecnológicas
* Pods Solid: para mejorar la seguridad y privacidad de los datos de los usuarios, se ha impuesto como una condición necesaria el uso de los pods (no una base de datos centralizada). Los pods almacenan independientemente la información de cada usuario.

.Tecnologías y motivación

* React: Framework de código abierto concebida para crear interfaces de usuario. Hemos elegido React por su sencillez y las númerosas posibilidades que proporciona, entre ellas desarrollar aplicaciones web multiplataforma.

* Docker: es un proyecto de código abierto que automatiza el despliegue de aplicaciones dentro de contenedores de software, proporcionando una capa adicional de abstracción.

.Forma
* Seguridad y privacidad: se mejorará la seguridad del usuario debido a que sus datos serán almacenados de forma descentralizada en los PODs.

* Diseño: vamos a utilizar el MVC (Modelo Vista Controlador)para facilitar el desarrollo, la limpieza de código y la organización del mismo.

* Desarrollo y reparto: Dividimos el trabajo por partes de la aplicación. Por ejemplo 2 integrantes del equipo se encargan del login, otros 2 del mapa y asi hasta cubrir todos los componentes de la aplicación.

* Usabilidad-Accesibilidad: intentaremos hacer la aplicación lo más accesible posible para facilitar en la medida de lo posible el uso de la aplicación para personas con alguna discapacidad.

