[[section-building-block-view]]


== Vista de bloques
=== Sistema general

Motivacion::
Describimos el alcance y contexto de nuestra aplicación.
Bloques de construcción contenidos::
-  **LoMap**: Nuestra aplicacion que gestiona lugares interesantes para los usuarios
-  **POD**: Lugar donde se almacenará la informacion de los usuarios, de forma mas personal(lugares o sitios de summo interes).
Interfaces importantes::
-Para conectarnos a los mapas y añadir etiquetas usaremos la api de mapas correspondiente(mapbox).

=== Nivel 2

Motivacion::
A continuación mostramos como ira implementada nuestra aplicacion
Bloques de construcción contenidos::
-  **Front-End**: Para la interfaz de usuario, como tecnología usaremos React.

Interfaces importantes::
-	Con las diferentes apis conectaremos el front-end y el back-end.

=== Nivel 3

Motivacion::
A continuación mostramos los modulos del back-end
Bloques de construcción contenidos::
-  **Main**: Con él comunicamos como forma principal el front-end y los pods.
-  **Solid**: Interactuará con el Pod(los pods seran de inrupt) del usuario.
-  **MapBox**: Api que se usara para los mapas.

Interfaces importantes::
- Para conectarnos a los mapas y añadir etiquetas usaremos la api de mapas correspondiente(mapbox).
- Para conectarnos a los pods usaremos como proveedor de los mismos a inrupt.