[[section-runtime-view]]
== Runtime View

[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

== Escenario de ejecución 1. Registro de nuevo usuario

[plantuml,"Sequence diagram",png]
----
actor User
database POD
database BBDD
entity LoMap
entity Api_Rest

User -> LoMap: El user rellena un formulario e introducir un Pod
LoMap -> Api_Rest: Se envía el formulario
Api_Rest -> POD: Almacena datos del usuario
Api_Rest -> BBDD: Envía datos necesarios
LoMap <- Api_Rest: Devuelve la confirmación del registro
User -> LoMap: Muestra un mensaje de confirmación

----
=== Escenario de ejecución 2. Inicio de sesion de usuario
[plantuml,"Sequence diagram1",png]
----
actor User
database POD
database BBDD
entity LoMap
entity Api_Rest

User -> LoMap: Introduce su pod 
LoMap -> Api_Rest: envía el pod
Api_Rest <- POD: Extrae datos del usuario
Api_Rest <- BBDD: Recibe datos necesarios
LoMap <- Api_Rest: Devuelve localizaciones
User -> LoMap: Muestra localizaciones
----
=== Escenario de ejecución 3. Añadir localización

Las ubicaciones guardadas pueden ser vistas más tarde por el usuario y sus amigos a través de la aplicación web.

El usuario puede agregar una ubicación a su mapa. 

[plantuml,"Sequence diagram - Saving Locations - mobileapp",png] 
----
actor User 
entity Api_Rest
database POD 
 
User-> Server: El usuario hace clic en el mapa para agregar un nuevo marcador 
Server ->Pod: Preguntar ubicaciones JSON 
Pod-> Server: Ubicaciones de retorno JSON
Server -> Server: Agregar la nueva ubicación
Server ->Pod: Envía el nuevo JSON
Server ->User: Muestra el mapa con la nueva ubicación
----  
=== Escenario de ejecución 4. Eliminar localización 

Las ubicaciones agregadas al mapa luego serán eliminadas por el usuario a través de la aplicación.

[plantuml,"Sequence diagram - Editing Saved Locations",png] 
---- 
actor User 
entity Api_Rest
database POD 
 
User-> Api_Rest: El usuario hace clic en el mapa en una ubicación de marca 

Api_Rest -> Api_Rest: Usando la ID de ubicación, la aplicación conoce el archivo JSON 
Api_Rest ->POD: Preguntar ubicaciones JSON
POD-> Api_Rest: Return locations JSON 
Api_Rest -> Api_Rest: Ubicaciones de retorno JSON
Api_Rest ->POD: Envía el nuevo JSON
Api_Rest ->User: Muestra el mapa con la nueva ubicación

---- 
=== Escenario de ejecución 5. Usuario visualiza una de sus localizaciones.
[plantuml,"Sequence diagram2",png]
----
actor User
database POD
database BBDD
entity LoMap
entity Api_Rest

User -> LoMap: Selecciona la localización
LoMap -> Restapi: Pide la información sobre esa localización 
Api_Rest -> POD: Busca datos sobre la localización
Api_Rest -> BBDD: Busca datos sobre la localización
Api_Rest <- POD: Devuelve los datos encontrados
Api_Rest <- BBDD: Devuelve los datos encontrados
LoMap <- Api_Rest: Devuelve la información que encontro
User -> LoMap: Muestra esa información
----
