[[section-deployment-view]]

== Vista de Despliegue

=== Infraestructura

Motivacion::

Se ha intentado plantear el sistema de la manera más descentralizada posible y mantener la privacidad del usuario de 
manera más optima posible.
Como provedor de PODs usamos inrupt ya que nos facilita mucho el desarrollo del proyecto y tiene una fácil comunicación con la aplicación.

Caracteristicas de calidad y/o rendimiento::

Como nuestro objetivo es tener un sistema con alto rendimiento,seguridad y mantenible con el tiempo se ha 
intentado buscar y comenzar a usar la mejor infraestructura posible.

Mapeo de Bloques de Construccion a Infraestructura::

[options="header",cols="1,2"]
|===
|Building Block|Mapping
| WebApp| La parte donde el usuario podra interactuar, el cual ejecuta el navegador web.
| Web browser| Depende de la eleccion del usuario, y unica forma de acceder a la aplicacion.
| POD| "Almacenes" para guardar los datos de los usuarios de forma segura. el provedor de pods sera inrupt
| Servidor Inrupt| Servicio descentralizado para almacenas los PODS de los usuarios que se registren en él. Cada POD contiene información única de cada usuario.
| GitHub | Servicio de control de versiones, donde se almacena el código fuente de la aplicación.
| GitHub Pages| Servicio de hosting de GitHub, donde se almacena el código compilado de la aplicación.
|===